name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 1 * *' # Monthly

jobs:
  win32:
    name: Win32
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Visual C++ 6.0
      run: |
        git clone --depth 1 https://github.com/SmileyAG/MSVC600
    - name: Build
      shell: cmd
      run: |
        call MSVC600/VC98/Bin/VCVars32.bat
        cd src_main
        call build_hl2_game.bat
        call build_hl1_game.bat
        call build_cs_game.bat
        call build_tf2_game.bat
        call build_engine.bat
        call build_vphysics.bat
    - name: Upload arficacts
      uses: actions/upload-artifact@v3
      with:
        name: Win32
        path: |
          src_main/cl_dll/cl_dll___Win32_HL2_Release/client.dll
          src_main/cl_dll/cl_dll___Win32_HL2_Release/client.pdb
          src_main/cl_dll/cl_dll___Win32_HL2_Debug/client.dll
          src_main/cl_dll/cl_dll___Win32_HL2_Debug/client.pdb
          src_main/cl_dll/cl_dll___Win32_HL1_Release/client.dll
          src_main/cl_dll/cl_dll___Win32_HL1_Release/client.pdb
          src_main/cl_dll/cl_dll___Win32_HL1_Debug/client.dll
          src_main/cl_dll/cl_dll___Win32_HL1_Debug/client.pdb
          src_main/cl_dll/Release_CounterStrike/client.dll
          src_main/cl_dll/Release_CounterStrike/client.pdb
          src_main/cl_dll/Debug_CounterStrike/client.dll
          src_main/cl_dll/Debug_CounterStrike/client.pdb
          src_main/cl_dll/cl_dll___Win32_TF2_Release/client.dll
          src_main/cl_dll/cl_dll___Win32_TF2_Release/client.pdb
          src_main/cl_dll/cl_dll___Win32_TF2_Debug/client.dll
          src_main/cl_dll/cl_dll___Win32_TF2_Debug/client.pdb
          src_main/dlls/Release_hl2/server.dll
          src_main/dlls/Release_hl2/server.pdb
          src_main/dlls/Debug_hl2/server.dll
          src_main/dlls/Debug_hl2/server.pdb
          src_main/dlls/Release_hl1/server.dll
          src_main/dlls/Release_hl1/server.pdb
          src_main/dlls/Debug_hl1/server.dll
          src_main/dlls/Debug_hl1/server.pdb
          src_main/dlls/Release_CounterStrike/server.dll
          src_main/dlls/Release_CounterStrike/server.pdb
          src_main/dlls/Debug_CounterStrike/server.dll
          src_main/dlls/Debug_CounterStrike/server.pdb
          src_main/dlls/Release_tf2/server.dll
          src_main/dlls/Release_tf2/server.pdb
          src_main/dlls/Debug_tf2/server.dll
          src_main/dlls/Debug_tf2/server.pdb
          src_main/engine/GLRelease/engine.pdb
          src_main/engine/GLRelease/engine.dll
          src_main/engine/GLDebug/engine.dll
          src_main/engine/GLDebug/engine.pdb
          src_main/vphysics/Release/vphysics.dll
          src_main/vphysics/Release/vphysics.pdb
          src_main/vphysics/Debug/vphysics.dll
          src_main/vphysics/Debug/vphysics.pdb
